# Generated by Django 5.2 on 2025-04-21 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_name', models.CharField(max_length=100)),
                ('plant_type', models.CharField(max_length=100)),
                ('soil_ph', models.FloatField()),
                ('soil_moisture', models.FloatField()),
                ('soil_air', models.FloatField()),
                ('soil_temp', models.FloatField()),
                ('organic_matter', models.FloatField()),
                ('ambient_temp', models.FloatField()),
                ('humidity', models.FloatField()),
                ('light_intensity', models.FloatField()),
                ('nitrogen_level', models.FloatField()),
                ('potassium_level', models.FloatField()),
                ('phosphorus_level', models.FloatField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lands', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
