# Generated by Django 5.2 on 2025-04-22 01:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='land',
            name='owner',
        ),
        migrations.AddField(
            model_name='land',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='land',
            name='land_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='land',
            name='plant_type',
            field=models.CharField(max_length=255),
        ),
    ]
