# Generated by Django 5.2 on 2025-04-22 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_land_owner_land_user_alter_land_land_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Land',
        ),
    ]
