# Generated by Django 5.2 on 2025-04-22 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_land'),
    ]

    operations = [
        migrations.RenameField(
            model_name='land',
            old_name='ambient_temp',
            new_name='ambientTemp',
        ),
        migrations.RenameField(
            model_name='land',
            old_name='land_name',
            new_name='landName',
        ),
        migrations.RenameField(
            model_name='land',
            old_name='light_intensity',
            new_name='lightIntensity',
        ),
        migrations.RenameField(
            model_name='land',
            old_name='nitrogen_level',
            new_name='nitrogenLevel',
        ),
        migrations.RenameField(
            model_name='land',
            old_name='organic_matter',
            new_name='organicMatter',
        ),
        migrations.RenameField(
            model_name='land',
            old_name='phosphorus_level',
            new_name='phosphorusLevel',
        ),
        migrations.RenameField(
            model_name='land',
            old_name='plant_type',
            new_name='plantType',
        ),
        migrations.RenameField(
            model_name='land',
            old_name='potassium_level',
            new_name='potassiumLevel',
        ),
        migrations.RenameField(
            model_name='land',
            old_name='soil_air',
            new_name='soilAir',
        ),
        migrations.RenameField(
            model_name='land',
            old_name='soil_moisture',
            new_name='soilMoisture',
        ),
        migrations.RenameField(
            model_name='land',
            old_name='soil_ph',
            new_name='soilPH',
        ),
        migrations.RenameField(
            model_name='land',
            old_name='soil_temp',
            new_name='soilTemp',
        ),
    ]
