# Generated by Django 5.2 on 2025-04-27 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_diseasedetection'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='disease',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='land',
            name='landStatus',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
