# Generated by Django 5.2 on 2025-04-28 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_land_disease_land_landstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseasedetection',
            name='image',
            field=models.ImageField(upload_to='disease_images/'),
        ),
    ]
