# Generated by Django 5.2 on 2025-04-29 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_diseaseimage_delete_diseasedetection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='land',
            name='disease',
        ),
        migrations.RemoveField(
            model_name='land',
            name='landStatus',
        ),
    ]
