# Generated by Django 5.2 on 2025-04-30 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_land_disease_remove_land_landstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='chlorophyllContent',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='land',
            name='electrochemicalSignal',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='land',
            name='soilType',
            field=models.CharField(default='Loamy', max_length=100),
        ),
    ]
