# Generated by Django 5.2 on 2025-05-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_conversationhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='last_detected_disease',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
