# Generated by Django 5.2 on 2025-06-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_land_last_detected_disease'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='article_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_approved_publisher',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('user', 'User'), ('publisher', 'Publisher'), ('administrator', 'Administrator')], default='user', max_length=20),
        ),
    ]
