# Generated by Django 5.2 on 2025-06-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_publisherapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='article_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
