# Generated by Django 5.2 on 2025-06-04 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_land_plant_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='land',
            name='plant_status',
        ),
    ]
