# Generated by Django 5.2 on 2025-06-04 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_remove_land_plant_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisherapplication',
            name='article_link',
            field=models.URLField(max_length=1000),
        ),
    ]
