# Generated by Django 5.2 on 2025-06-05 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_publisherapplication_article_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisherapplication',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
