# Generated by Django 5.2 on 2025-06-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_publisherapplication_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='plant_status',
            field=models.CharField(default='Healthy', max_length=50),
        ),
    ]
