# Generated by Django 5.2 on 2025-06-05 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_land_plant_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisherapplication',
            name='password',
            field=models.CharField(default='temp1234', max_length=128),
            preserve_default=False,
        ),
    ]
