# Generated by Django 5.2 on 2025-06-06 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_publisherapplication_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
            ],
            options={
                'verbose_name': 'Administrator',
                'verbose_name_plural': 'Administrators',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.customuser',),
        ),
        migrations.AlterField(
            model_name='publisherapplication',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='publisherapplication',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='publisherapplication',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='publisherapplication',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_profiles_allowed', models.IntegerField(default=0)),
                ('ai_assistant', models.BooleanField(default=False)),
                ('disease_detection', models.BooleanField(default=False)),
                ('hardware_streaming', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
