# Generated by Django 5.2 on 2025-06-07 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_administrator_alter_publisherapplication_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kits', models.PositiveIntegerField(default=1)),
                ('type', models.CharField(choices=[('hardware', 'Hardware'), ('setup', 'Setup')], default='hardware', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('refused', 'Refused')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
