# Generated by Django 5.2 on 2025-06-07 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_hardwarerequest_email_hardwarerequest_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardwarerequest',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
