# Generated by Django 5.2 on 2025-06-07 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_hardwarerequest_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisherapplication',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
