# Generated by Django 5.2 on 2025-06-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_alter_publisherapplication_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='land_profiles_allowed',
            field=models.IntegerField(default=1),
        ),
    ]
