# Generated by Django 5.2 on 2025-06-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_alter_publisherapplication_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='ai_assistant_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='disease_detection_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='hardware_streaming_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
