# Generated by Django 5.2 on 2025-06-08 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_subscription_ai_assistant_expires_at_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='land',
            constraint=models.UniqueConstraint(fields=('user', 'landName'), name='unique_land_per_user'),
        ),
    ]
